### ISSUE TITLE
Email passed and filtered at the same time (schrodinger email)

### ISSUE THREAD

**Issue by barthoi** [Probesys/agentj#13]
Hi there,

I had an issue with AgentJ passing email when it should filter them. You fixed it today thanks! As requested, this issue for the followup.

Alice send an email to Bob
1- Bob receives the email
2- Alice receives the captcha email
3- Alice validated the captcha
4- Bob receives again the email

I've been playing with the configuration and probably this was the sequence which created the problem : 
- After installing AgentJ with docker
- Setting the domain with parameter "All all emails"+"Pas de censure"
- Declaration of an email user
- Changing the domain policy from "All all emails"+"Pas de censure" to "Block all mails"+"Normale"

Thanks again !

**Comment by ctresvaux** [comment]
Hi Baptiste and thank you for your feedback.
The bug is fixed in release 1.5.1.
The problem you encountered was : 
You created a domain with "Pas de censure" as policy. You added a user account to this domain
This policy mark a mail as spammed but relay it anyway.
The bug was that when you change the domain policy the users policy was not updated. 
his now fixed.

Regards
