### ISSUE TITLE
Ability to install AgentJ without Docker

### ISSUE THREAD

**Issue by Dual-Boot** [Probesys/agentj#8]
Hello,

 I think everything is in the title ;) . The purpose is to be able to plug AgentJ to an existing Mail/MTA infra .
 If so, is there a documentation ?

   Regards,

**Comment by sjpp** [comment]
Hello,
User and admin documentation is a *work in progress*, we'll update the README once it's ready.
At the moment, we only document the Docker deployment as it is, for most use cases, the most convenient way to deploy and use it.
AgentJ does not provides a full MTA infrastructure, it comes in front of it so that you can keep on using your existing mail stack.

If you simply want to try it, all you have to do is:
- set your domain and MTA server in the `.env` file (and other vars, see README)
- deploy it via `docker-compose up -d`
- log in as *admin* and configure your domain, this is where you will indicate your existing SMTP server hostname and port as well as your IMAP server (used for users authentication)
- then use a mail tool such as [swaks](http://www.jetmore.org/john/code/swaks/) to make mail delivery tests
- if everything suit your needs and you want to use AgentJ in production, simply point your domain MX DNS RR to the IP of the server running AgentJ.

Regards,

**Comment by Dual-Boot** [comment]
Hello,

 Thank you for this reply. I am not a fan of Docker, I prefer without it. Docker adds a layer of complexity that blurs how really works a software.
 Regards,

**Comment by sjpp** [comment]
Sure it does bring complexity but it is convenient for most deployment.
Yet, you can use only the frontend (which source code is in the `app` folder) but then you will have to set up the whole environment (Amavis, MariaDB, set up the database for Amavis (it is in Amavis' documentation), the Web proxy, ...) and configure everything to fit in your current mail infrastructure.

**Comment by sjpp** [comment]
I am closing this issue as we have no plan to provide or support AgentJ deployments and usages without its docker-based infrastructure.
